### ISSUE TITLE
how do I make it work on embeded videos?

### ISSUE THREAD

**Issue by sdsucks** [erkserkserks/h264ify#1]
I see no option?
do I have to click "play on youtube" everytime?

**Comment by prakharbahuguna** [comment]
The extension is set to only activate on YouTube itself. Allowing access on all websites will allow it to block WebM when a YouTube video is embedded in another website.

**Comment by martindale** [comment]
Actually, shouldn't the extension work as-is if the YouTube video is an embedded iframe?

**Comment by erkserkserks** [comment]
Added "all_frames": true to the manifest. Thanks for the tip @martindale!
