### ISSUE TITLE
Force Youtube to use 30fps version of 1080p and 720p?

### ISSUE THREAD

**Issue by xiaozj** [erkserkserks/h264ify#11]
For older AMD APUs such as the Zacate E350 which I personally have, hardware h264 decode supports end at 1080p 30fps.

So with any Youtube video that is 60fps, I am out of luck as video stutters like no tomorrow and is unwatchable.

I can watch these videos in 1080p30 in Internet Explorer so the streams are there, just not exposed to Chrome.

Is it possible to add an option to force videos to 30fps even when 60fps is available?

**Comment by erkserkserks** [comment]
Hello,

Can you provide an example video?

**Comment by xiaozj** [comment]
Hi, this Starcraft 2 gameplay video illustrate this well https://www.youtube.com/watch?v=2SbMVuEwzlg

**Comment by erkserkserks** [comment]
Hello,

Please try this modified extension: https://github.com/erkserkserks/h264ify/raw/block-60fps-video/h264ify.crx

This will attempt to block any >30fps video

**Comment by xiaozj** [comment]
Thanks a bunch! That worked perfectly!

**Comment by xiaozj** [comment]
Is it possible to make it a feature of the official version of the extension?

It seems that Chrome will block non-Web Store extensions after every update.

**Comment by erkserkserks** [comment]
Hello,

I'm planning to add this feature (along with a few others) to the next version of h264ify, but unfortunately I don't have a ETA (busy with school). Hopefully within the next few weeks.

**Comment by erkserkserks** [comment]
The new version (v1.0.3) has an option to block 60fps videos. Let me know if this works for you (you may have to wait until Google pushes the new version out).

**Comment by xiaozj** [comment]
Got the update, thanks a bunch!

**Comment by viotuto** [comment]
Works Great. I love it.
U should publish it in chrome web store.

**Comment by Mangerzz** [comment]
Ey men! thnks for the extension. im very happy. me internet conection is 1mb. i cannot whatch 60fps videos in 1080p  but  in 30fps i can >_< <3 <3 <3!!!

**Comment by chummy02** [comment]
For me this is not working with Firefox 52.0b2 (64-bit). Block 60fps keep playing 60fps content anyway, can someone confirm if its just me?

**Comment by erkserkserks** [comment]
What is your operating system? Can you provide an example video which you are seeing this problem?

**Comment by chummy02** [comment]
I'm using Windows 10 latest stable build 14393.693. A video example which has 1080p@50fps when block 60fps only display 480p25 and lower resolutions: https://www.youtube.com/watch?v=2p0o2PFvwyk

Something which is not talk is than Youtube not only support high framerate from 60fps but it support too a range from 46 to 50fps.

Just to be fair the 60fps block is working for some 60fps videos like this: https://www.youtube.com/watch?v=qX9k9XaBcAg
