### ISSUE TITLE
Suddenly can't seek through timeline.

### ISSUE THREAD

**Issue by sooqua** [erkserkserks/h264ify#18]
I used this extension for a long time and I loved it but recently (yesterday?) videos started to lag and I couldn't seek through timeline. Disabling this extension makes me able to seek but my old laptop can't play 1080p@60 videos without it =(
Please help me.

**Comment by sooqua** [comment]
Fixed it 😆 
Enabled **WebRTC H.264 software video encoder/decoder** in [chrome://flags/](chrome://flags/)

**Comment by sooqua** [comment]
It didn't fixed it 😞

**Comment by erkserkserks** [comment]
Hello, what chrome version and operating system? How often does this happen?

**Comment by sooqua** [comment]
I'm sorry, the problem had nothing to do with your extension. I had to disable **Hardware-accelerated video decode**
