### ISSUE TITLE
After forking and updating code, I'm realizing I should break this off into another project

### ISSUE THREAD

**Issue by mtomasek780** [erkserkserks/h264ify#25]
I forked this project to solve an issue that can be found [here](https://forum.vivaldi.net/topic/11979/videos-not-playing-browser-needs-manual-restart-a-lot) with Vivaldi's UI.  After playing with the code, I realized I needed to open the inspection of traffic to <all_urls> as opposed to just YouTube as the issue exists everywhere where mp4 files are served (CNN, Twitter Video, Youtube, and more).  You can see my fork here and the code works great after some light testing, but I haven't cleaned it up yet to be more efficent since dropping mp4, webm, vp8, and vp9 just results in Flash Player coming up and I'm just making the world a worse place at that point.

Since this project is MIT licensed, I'm going to setup my own repository and work on establishing my own chrome store approval. Since this is the first time I've forked a project, set up a repository, and using a ton of code that was previously created, I wanted to see if you had any preferences in receiving credit for your work in addition to the light terms of the MIT.  I'm planning on plugging your project and linking back to here for reference as this isn't possible without seeing this project, is there anything else I can do out of courtesy to you and the contributors? I'm more than happy keeping the code here and setting up a pull request once I clean-up the code to not modify as much as it does in comparison (my fault as a GitHub newbie), but I don't see a way we can be compatible with the need for <all_urls> being needed.

Regards,
Mike

**Comment by mtomasek780** [comment]
The code is continually changing, I will just respect the MIT and give you guys a plug on the site if and when I put it live...  Thanks!

**Comment by erkserkserks** [comment]
Good luck with your project!
