### ISSUE TITLE
Publish on addons.mozilla.org?

### ISSUE THREAD

**Issue by eoger** [erkserkserks/h264ify#29]
[erkserkserks/h264ify-firefox](https://github.com/erkserkserks/h264ify-firefox/) will be incompatible with Firefox starting in version 57.  

[Firefox now implements most of the chrome.* APIs](https://arewewebextensionsyet.com/).  
I tested this version of h264ify and it works without any modification of the source code. You can try it out yourself by navigating to about:debugging, clicking "Load temporary addon" and selecting the manifest.json file.
Would you care to update the [version published on addons.mozilla.org](https://addons.mozilla.org/en-US/firefox/addon/h264ify/) with this one?

**Comment by MikkCZ** [comment]
@erkserkserks if you are interested, I can help you with testing this on my Linux machine.

**Comment by erkserkserks** [comment]
The Firefox extension is now a web extension as of v1.0.6!
