### ISSUE TITLE
Permission to access your data ...

### ISSUE THREAD

**Issue by BqB6tG2lh4Buz** [erkserkserks/h264ify#38]
More info please about "... h264ify requires permission to access your data for sites in youtube.com domain...". Could you give more insight on this? With Firefox 57, would this data be also logged on the home computer's Firefox plugin data. Any insight on this matter would be appreciated. Sorry, i'm code illiterate. Using Win7 with Firefox 57.0 64bit. Regards and thank you.

**Comment by erkserkserks** [comment]
h264ify requires that permission to inject a script into all youtube.com pages. Basically, the script makes the browser appear as if it doesn't support playing vp9, which forces youtube to serve h.264 content. No data is logged, stored, or transmitted.
