### ISSUE TITLE
Trying to make it work

### ISSUE THREAD

**Issue by sergeevabc** [erkserkserks/h264ify#4]
Dear @erkserkserks, could you investigate why h264ify makes no expected impact on Chromium 44? Yes, it disables WebM, but H264 is still not available. P.S. GPU [page says][1] acceleration’s enabled.

![](http://i.imgur.com/82gmIY1.png)
[1]: https://cloudup.com/cN4FLs0ikxd

**Comment by erkserkserks** [comment]
What does https://www.youtube.com/html5 look like without h264ify installed?

**Comment by sergeevabc** [comment]
WebM VP8 and 9 are enabled without h264ify installed.

!(http://i.imgur.com/wT2BfDQ.png)

**Comment by erkserkserks** [comment]
Chromium doesn't have h.264 support, see https://code.google.com/p/chromium/wiki/ChromiumBrowserVsGoogleChrome

**Comment by sergeevabc** [comment]
Thanks for investigation, @erkserkserks.
Indeed, Chromium lacks [support of proprietary codecs][1].
Consider mentioning this fact somewhere in extension’s description.

[1]: http://chromium.woolyss.com/#features
