### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by Stryxus** [erkserkserks/h264ify#40]
I used this extension for Chrome but since, Edge has snatched me (Mainly because I agree that internet browsers should have a fair share of the browsing ecosystem and chrome owns more than 75% of it) and from what iv seen with the differences of the Chromes and Edges extension api's, they don't seem that different.

I would help make this but I know very little about video codecs and don't feel like I am skilled enough to contribute to this extension yet.

**Comment by alejandrojara** [comment]
Ported it following this Microsoft Guide [1] and it works almost perfectly (it lacks accesible options menu to disable 60fps). You should try it.

[1]: https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions

**Comment by erkserkserks** [comment]
Edge version: https://microsoftedge.microsoft.com/addons/detail/ldjamdlpbjpcfagnckgipdjiamhdcnbd?hl=en-US
