### ISSUE TITLE
Safari support?

### ISSUE THREAD

**Issue by chris1000** [erkserkserks/h264ify#44]
Would it be possible to port the extension itself to safari or make it into a Greasemonkey script that way it can be installed on any browser

**Comment by erkserkserks** [comment]
There is a user script (not written by me) that disables vp9: https://greasyfork.org/en/scripts/8128-youtube-h-264/code

However, Safari doesn't support vp9 so it should play h264 by default. The one benefit h264ify does have, however is blocking 60fps playback.
