### ISSUE TITLE
Extension icon is greyed out and extension is not working

### ISSUE THREAD

**Issue by jenthura** [erkserkserks/h264ify#45]
From what I've read, this means that the extension was installed from outside of the app store, but that's not true with how I installed this extension. Does it need an update? I've already updated chrome and uninstalled and reinstalled the extension.

**Comment by erkserkserks** [comment]
I also see this issue, even when installing from the store. I'm currently
out of town, but will look at this when I return.

**Comment by jenthura** [comment]
I appreciate it!

**Comment by llamantin** [comment]
Hello, same problem here. Installed from the store page and the icon is grey, doesn't work

**Comment by NoMod-Programming** [comment]
For me, the extension works but is greyed out still. Using Chrome 67.0.3396.99 (Official Build) (64-bit) (cohort: Stable)

**Comment by erkserkserks** [comment]
The latest release v1.0.8 should fix this issue
