### ISSUE TITLE
Extension not working on some embedded videos

### ISSUE THREAD

**Issue by dnmTX** [erkserkserks/h264ify#47]
Windows 10 x64 Enterprise LTSB 1607
Slimjet Browser (based on Chromium 68.0.3440.75) (Official Build) (64-bit)

Extension doesn't kick in on some embedded videos as observed here:
http://www.guru3d.com/news-story/military-operations-benchmark-released.html

I'm hoping that dev still maintaining it and the issue will be resolved.We need it working,helps a lot on older systems.Thank you.

![vp9](https://user-images.githubusercontent.com/34774426/41803002-a5dad68a-764a-11e8-9e15-cfbab39ef39a.png)

**Comment by dnmTX** [comment]
@erkserkserks  it actually start happening on every page with embedded youtube link.On the actual youtube site the extension is working as intended.Here is more fresh links:

https://www.techpowerup.com/247624/katamari-damacy-comes-to-the-pc-as-a-remastered-edition

https://www.guru3d.com/
(scroll down until you see  the player-Forza Horizon 4 video)

**Comment by dnmTX** [comment]
@erkserkserks  i was looking into the page code(not sure if this is matter but just in case) and the player is fetched from `s.ytimg.com` domain.The actual link is:
https://s.ytimg.com/yts/jsbin/player-vflkUTZn2/en_US/base.js
Will attach the script where i found all the codecs listed,hopefully can help you figure it out why it doesn't work.
[base.zip](https://github.com/erkserkserks/h264ify/files/2387378/base.zip)

**Comment by dnmTX** [comment]
.....errors that i see in chrome dev tools:

`Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at chrome-extension://aleakchihdccplidncghkekgioiakgal/src/inject/content_script.js:30:1`

![capture](https://user-images.githubusercontent.com/34774426/45606782-a297d200-ba0d-11e8-83b7-f218b75fcc93.PNG)

**Comment by dnmTX** [comment]
**UPDATE:** Ok...i got it working at guru3d.com.Had to allow cookies for youtube.com to be stored.Third party cookies were disabled that's why.No luck at techpowerup.com though.No errors showing in dev tools,i'm out of ideas on this one.

**Comment by erkserkserks** [comment]
@avi12 If you want to push to this repository, you'll have to create a pull request first.

@dnmTX Try the new version (v1.0.9) of h264ify. I've added more youtube domains that this extension will run on, which should solve your issue.

**Comment by dnmTX** [comment]
@erkserkserks  tested,finally success 👍  on techpowerup.com. Good job,thank you for fixing it.The difference is,to make it work i had to allow `youtube-nocookie.com` to store cookies as i did for guru3d.com. With @avi12's extension,after he pushed the fix i didn't have to do that.Still,it works so i'm happy.
@avi12 thanks for pitching in man,very much appreciate the effort 👍

**Comment by avi12** [comment]
> @avi12 If you want to push to this repository, you'll have to create a pull request first.

I pulled via WebStorm, then attempted to commit & push. Still got that error
> @avi12 thanks for pitching in man,very much appreciate the effort 👍

No problem 😄

**Comment by dnmTX** [comment]
@avi12 
> I pulled via WebStorm, then attempted to commit & push. Still got that error

You can do it straight from the browser here,no need of additional programs for that.It's really easy,once you've done the changes you'll see there is a button to make pull request. I've done it several times and i'm not a coder or something(very limited knowledge),pretty sure it will be "walk in the park for ya" 👍

**Comment by avi12** [comment]
Well, I have no idea what is it talking about. From my manifest:
![webstorm64_2018-09-22_22-03-44](https://user-images.githubusercontent.com/6422804/45920872-6358fd80-beb3-11e8-93f7-2dd97728484f.png)
Maybe the permissions are associated with another extension?

**Comment by dnmTX** [comment]
Oh...i see,well,that make sense.Thanks for clarifying it @avi12 ,just had to make sure.
Cheers!

**Comment by avi12** [comment]
And since it didn't seem to break anything in my extension, I removed it. One less permission

**Comment by dnmTX** [comment]
Closing this to reduce the clutter.Thank you @erkserkserks  and @avi12 .Keep up the **GOOD WORK** guys!
