### ISSUE TITLE
Resolutions higher than 1080p (especially 1440p and 4K) are not available.

### ISSUE THREAD

**Issue by Piter432** [erkserkserks/h264ify#5]
As title says. Some videos offers 1440p or 4K, but this resolutions are not available, while h264ify is on in Chrome.

**Comment by Piter432** [comment]
Why you don't answer me or fix this problem, if it's possible?

**Comment by kuc** [comment]
He wasn't online for a long time: https://github.com/erkserkserks?tab=activity

**Comment by erkserkserks** [comment]
Hello, can you post an example video where 4k is available when h264ify is enabled?

**Comment by Piter432** [comment]
@erkserkserks Sure. Here is 4K video at 30 fps: https://www.youtube.com/watch?v=mkOXrd-zxVs
And here are 4K videos at 60 fps from playlist by YouTube, which currently testing the 1440p and 4K quality videos at 60 fps: https://www.youtube.com/watch?v=-iSFM-T-F_0&list=PLyqf6gJt7KuHCoYaGNWPx8vkHlClmbO9u

Both 1440p and 4K videos at 30 fps and 60 fps doesn't have 1440p and 4K qualities available, when H264ify is enabled in Firefox and Chrome. I don't know it's possible to fix (I'm totally zero at programming and coding apps, programs, etc.), but if yes, please fixt it :)

**Comment by erkserkserks** [comment]
Great, thanks for the video samples, I will take a look later tonight.

**Comment by erkserkserks** [comment]
Okay, I looked at the videos and I was able to get the 30fps video to play at 4k. The 60fps video I could only get it to play at 1080p60.

Does this video play in 4k for you? https://www.youtube.com/watch?v=wTcNtgA6gHs

Can you visit the following page and tell me what your browser supports? https://www.youtube.com/html5

And finally, can you visit the following page and post what it says? chrome://gpu/

**Comment by Piter432** [comment]
<blockquote>Does this video play in 4k for you? https://www.youtube.com/watch?v=wTcNtgA6gHs</blockquote>
This video play both in 4K and 1440p


<blockquote>Can you visit the following page and tell me what your browser supports? https://www.youtube.com/html5</blockquote>
Only WebM VP8 and MSE & WebM VP9 have red warnings,


<blockquote>And finally, can you visit the following page and post what it says? chrome://gpu/</blockquote>
Graphics Feature Status
- Canvas: Hardware accelerated
- Flash: Hardware accelerated
- Flash Stage3D: Hardware accelerated
- Flash Stage3D Baseline profile: Hardware accelerated
- Compositing: Hardware accelerated
- Multiple Raster Threads: Enabled
- Rasterization: Hardware accelerated
- Threaded Rasterization: Enabled
- Video Decode: Hardware accelerated
- Video Encode: Hardware accelerated
- WebGL: Hardware accelerated

I'm posting this issue from my mom's laptop (HP Pavilion dv7) and I have enabled "ignore-gpu-blacklist" in chrome://flags/

**Comment by erkserkserks** [comment]
It appears that some videos on youtube are encoded in VP9 only, particularly the high resolution and high frame rate videos. I assume they're doing that to reduce bandwidth. Unfortunately in that case, there is no 4k h.264 stream available.

**Comment by Piter432** [comment]
What about 1440p at 60 fps with H264 stream?

**Comment by erkserkserks** [comment]
It is the same for 1440p at 60. YouTube does not produce an h264 stream for
that video resolution and frame rate.

**Comment by Piter432** [comment]
FFFFFFFFFFFFFFFFFFFFFFFUUUUUUUUUUUUUUUUUUUUUUUUUU! Damn YouTube :(

**Comment by Akababa** [comment]
It appears that some videos on youtube are encoded in VP9 only, particularly the high resolution and high frame rate videos. I assume they're doing that to reduce bandwidth. Unfortunately in that case, there is no 4k h.264 stream available.

This is impossible in the case of https://www.youtube.com/watch?v=Z6lYqgWAmrg, which plays absolutely fine at 4k60 in IE while consuming <5% cpu, meaning that it is H.264 hardware accelerated. However with h264ify in chrome it doesn't give the option for anything higher than 1080p60. See this reddit post https://www.reddit.com/r/chrome/comments/3o9dw5/youtube_playback_performance_issues/

**Comment by erkserkserks** [comment]
I don't have access to IE at the moment, could you right click the video, and post a screenshot of the "Stats for nerds" dialog box?

**Comment by Akababa** [comment]
I just noticed that it doesn't play at 60fps, my bad.
![screenshot 3](https://cloud.githubusercontent.com/assets/4205182/10437476/6d2db6ce-70fb-11e5-8944-f4fe4047ba78.png)
