### ISSUE TITLE
Doen't work for me - Chrome 43 on OS X 10.10.4

### ISSUE THREAD

**Issue by MrGluek** [erkserkserks/h264ify#7]
Hi.
Having trouble with high res (4k) videos, in Chrome,
but in Safari it's fine. Found topic:
https://code.google.com/p/chromium/issues/detail?id=456513
with link to h264ify, installed, but no effect, youtube still loading vp9 in chrome.

Chrome 43.0.2357.134 (64-bit)

On page
http://www.youtube.com/html5
- all checkmarks (including "WebM VP8" and "MSE & WebM VP9")

**Comment by MrGluek** [comment]
![image](https://cloud.githubusercontent.com/assets/11082640/8705642/aaa58878-2b33-11e5-9b8c-1baff8fbef61.png)

![image](https://cloud.githubusercontent.com/assets/11082640/8705654/b95e9a4e-2b33-11e5-8c24-fe0648acacf6.png)

![image](https://cloud.githubusercontent.com/assets/11082640/8705665/c5fcf46c-2b33-11e5-811b-500c5e5ee907.png)

**Comment by erkserkserks** [comment]
Look like the JS may not be injected properly. What happens when you run window.MediaSource.isTypeSupported("vp9") in the console?

**Comment by MrGluek** [comment]
Now it's work fine, found the problem - Adblock Plus extension. Deleting it (switched to uBlock) helps.
```
window.MediaSource.isTypeSupported("vp9")
false
```
