### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by nohzgul** [erkserkserks/h264ify#72]
Hi, can you make a version for Microsoft Edge?

**Comment by erkserkserks** [comment]
Yes, this is possible. I have submitted this extension to the Microsoft store and am awaiting a review. Out of curiosity, are you experiencing video playback issues due to VP9 on Edge?

**Comment by erkserkserks** [comment]
Edge version: https://microsoftedge.microsoft.com/addons/detail/ldjamdlpbjpcfagnckgipdjiamhdcnbd?hl=en-US
