### ISSUE TITLE
Donate button?

### ISSUE THREAD

**Issue by m1keil** [erkserkserks/h264ify#9]
Hey,
I'm really surprised I've never heard about this extension before.. It is a life saver!
Any chance I (and possibly others) can show my gratitude and buy you a beer or something?

Thanks!

**Comment by erkserkserks** [comment]
Thank you for your kind words! At the moment, there is no donate button, but I'll keep it in mind for v2 :)

**Comment by m1keil** [comment]
You can also add something such as Flattr directly to this repo.

Thanks again!
